---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-cluster-secrets
  namespace: kube-system
spec:
  dependsOn:
    - name: external-secrets
      namespace: kube-system
  releaseName: external-secrets-cluster-secrets
  chart:
    spec:
      chart: external-secrets-cluster-secrets
      version: 0.1.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets-cluster-secrets
        namespace: kube-system
#      verify:
#        provider: cosign
#        secretRef:
#          name: cosign-signing-key
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: cluster-metadata
      valuesKey: instance
      targetPath: clusterName
    - kind: Secret
      name: cluster-metadata
      valuesKey: vault_addr
      targetPath: vaultAddress
