---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.1.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: kube-system
#      verify:
#        provider: cosign
#        secretRef:
#          name: cosign-signing-key
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-release-values
      valuesKey: values.yaml
    - kind: Secret
      name: cluster-metadata
      valuesKey: management_node_group_name
      targetPath: external-secrets.nodeSelector.nodegroup
    - kind: Secret
      name: cluster-metadata
      valuesKey: management_node_group_role
      targetPath: external-secrets.tolerations[0].value
    - kind: Secret
      name: cluster-metadata
      valuesKey: management_node_group_name
      targetPath: external-secrets.certController.nodeSelector.nodegroup
    - kind: Secret
      name: cluster-metadata
      valuesKey: management_node_group_role
      targetPath: external-secrets.certController.tolerations[0].value
    - kind: Secret
      name: cluster-metadata
      valuesKey: management_node_group_name
      targetPath: external-secrets.webhook.nodeSelector.nodegroup
    - kind: Secret
      name: cluster-metadata
      valuesKey: management_node_group_role
      targetPath: external-secrets.webhook.tolerations[0].value
